steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: libarchive
  version: '>=0'
  category: app-arch
- name: json-glib
  version: '>=0'
  category: dev-libs
- name: libyaml
  version: '>=0'
  category: dev-libs
- name: snowball-stemmer
  version: '>=0'
  category: dev-libs
- name: fontconfig
  version: '>=0'
  category: media-libs-1.0
- name: freetype
  version: '>=0'
  category: media-libs-2
- name: libsoup
  version: '>=0'
  category: net-libs-2.4
- name: util-linux
  version: '>=0'
  category: sys-apps
- name: gtk+
  version: '>=0'
  category: x11-libs-3
- name: pango
  version: '>=0'
  category: x11-libs
