steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: perl
  version: '>=0'
  category: dev-lang
- name: double-conversion
  version: '>=0'
  category: dev-libs
- name: glib
  version: '>=0'
  category: dev-libs-2
- name: icu
  version: '>=0'
  category: dev-libs
- name: libpcre2
  version: '>=0'
  category: dev-libs
- name: systemd
  version: '>=0'
  category: sys-apps
