steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: zstd
  version: '>=0'
  category: app-arch
- name: p11-kit
  version: '>=0'
  category: app-crypt
- name: docbook-xsl-stylesheets
  version: '>=0'
  category: app-text
- name: elfutils
  version: '>=0'
  category: dev-libs
- name: lxml
  version: '>=0'
  category: dev-python
- name: gperf
  version: '>=0'
  category: dev-util
- name: intltool
  version: '>=0'
  category: dev-util
- name: qrencode
  version: '>=0'
  category: media-gfx
- name: libidn2
  version: '>=0'
  category: net-dns
- name: iptables
  version: '>=0'
  category: net-firewall
- name: libmicrohttpd
  version: '>=0'
  category: net-libs
- name: coreutils
  version: '>=0'
  category: sys-apps
- name: dbus
  version: '>=0'
  category: sys-apps
- name: kmod
  version: '>=0'
  category: sys-apps
- name: gnu-efi
  version: '>=0'
  category: sys-boot
- name: libapparmor
  version: '>=0'
  category: sys-libs
- name: libxkbcommon
  version: '>=0'
  category: x11-libs
