steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: bzip2
  version: '>=0'
  category: app-arch
- name: xz-utils
  version: '>=0'
  category: app-arch
- name: valgrind
  version: '>=0'
  category: dev-util
- name: flex
  version: '>=0'
  category: sys-devel
- name: gettext
  version: '>=0'
  category: sys-devel
- name: m4
  version: '>=0'
  category: sys-devel
- name: zlib
  version: '>=0'
  category: sys-libs
