steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: pax-utils
  version: '>=0'
  category: app-misc
- name: docbook-sgml-utils
  version: '>=0'
  category: app-text
- name: util-linux
  version: '>=0'
  category: sys-apps
- name: pam
  version: '>=0'
  category: sys-libs
