steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: File-Listing
  version: '>=0'
  category: dev-perl
- name: HTML-Parser
  version: '>=0'
  category: dev-perl
- name: HTTP-Cookies
  version: '>=0'
  category: dev-perl
- name: HTTP-Daemon
  version: '>=0'
  category: dev-perl
- name: HTTP-Negotiate
  version: '>=0'
  category: dev-perl
- name: Net-HTTP
  version: '>=0'
  category: dev-perl
- name: Try-Tiny
  version: '>=0'
  category: dev-perl
- name: WWW-RobotRules
  version: '>=0'
  category: dev-perl
