steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: flite
  version: '>=0'
  category: app-accessibility
- name: snappy
  version: '>=0'
  category: app-arch
- name: xz-utils
  version: '>=0'
  category: app-arch
- name: tesseract
  version: '>=0'
  category: app-text
- name: gmp
  version: '>=0'
  category: dev-libs
- name: libcdio-paranoia
  version: '>=0'
  category: dev-libs
- name: openssl
  version: '>=0'
  category: dev-libs
- name: librsvg
  version: '>=0'
  category: gnome-base-2
- name: aribb24
  version: '>=0'
  category: media-libs
- name: chromaprint
  version: '>=0'
  category: media-libs
- name: codec2
  version: '>=0'
  category: media-libs
- name: dav1d
  version: '>=0'
  category: media-libs
- name: fdk-aac
  version: '>=0'
  category: media-libs
- name: game-music-emu
  version: '>=0'
  category: media-libs
- name: kvazaar
  version: '>=0'
  category: media-libs
- name: libaom
  version: '>=0'
  category: media-libs
- name: libass
  version: '>=0'
  category: media-libs
- name: libbluray
  version: '>=0'
  category: media-libs
- name: libbs2b
  version: '>=0'
  category: media-libs
- name: libcaca
  version: '>=0'
  category: media-libs
- name: libdc1394
  version: '>=0'
  category: media-libs-2
- name: libiec61883
  version: '>=0'
  category: media-libs
- name: libilbc
  version: '>=0'
  category: media-libs
- name: libmodplug
  version: '>=0'
  category: media-libs
- name: libtheora
  version: '>=0'
  category: media-libs
- name: libv4l
  version: '>=0'
  category: media-libs
- name: libvpx
  version: '>=0'
  category: media-libs
- name: libwebp
  version: '>=0'
  category: media-libs
- name: lilv
  version: '>=0'
  category: media-libs
- name: nv-codec-headers
  version: '>=0'
  category: media-libs
- name: openal
  version: '>=0'
  category: media-libs
- name: opencore-amr
  version: '>=0'
  category: media-libs
- name: openh264
  version: '>=0'
  category: media-libs
- name: openjpeg
  version: '>=0'
  category: media-libs-2
- name: opus
  version: '>=0'
  category: media-libs
- name: raspberrypi-userland
  version: '>=0'
  category: media-libs
- name: rubberband
  version: '>=0'
  category: media-libs
- name: speex
  version: '>=0'
  category: media-libs
- name: vidstab
  version: '>=0'
  category: media-libs
- name: vo-amrwbenc
  version: '>=0'
  category: media-libs
- name: vulkan-loader
  version: '>=0'
  category: media-libs
- name: x264
  version: '>=0'
  category: media-libs
- name: x265
  version: '>=0'
  category: media-libs
- name: xvid
  version: '>=0'
  category: media-libs
- name: zimg
  version: '>=0'
  category: media-libs
- name: zvbi
  version: '>=0'
  category: media-libs
- name: frei0r-plugins
  version: '>=0'
  category: media-plugins
- name: gsm
  version: '>=0'
  category: media-sound
- name: lame
  version: '>=0'
  category: media-sound
- name: twolame
  version: '>=0'
  category: media-sound
- name: wavpack
  version: '>=0'
  category: media-sound
- name: rav1e
  version: '>=0'
  category: media-video
- name: rtmpdump
  version: '>=0'
  category: media-video
- name: samba
  version: '>=0'
  category: net-fs
- name: libssh
  version: '>=0'
  category: net-libs
- name: srt
  version: '>=0'
  category: net-libs
- name: zeromq
  version: '>=0'
  category: net-libs
- name: clang
  version: '>=0'
  category: sys-devel-10
- name: linux-headers
  version: '>=0'
  category: sys-kernel
- name: libavc1394
  version: '>=0'
  category: sys-libs
- name: libXv
  version: '>=0'
  category: x11-libs
- name: libva
  version: '>=0'
  category: x11-libs
- name: libvdpau
  version: '>=0'
  category: x11-libs
