steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
requires:
- name: gmp
  version: '>=0'
  category: dev-libs
- name: libcdio-paranoia
  version: '>=0'
  category: dev-libs
- name: librsvg
  version: '>=0'
  category: gnome-base-2
- name: codec2
  version: '>=0'
  category: media-libs
- name: fdk-aac
  version: '>=0'
  category: media-libs
- name: libbluray
  version: '>=0'
  category: media-libs
- name: libbs2b
  version: '>=0'
  category: media-libs
- name: libdc1394
  version: '>=0'
  category: media-libs-2
- name: libtheora
  version: '>=0'
  category: media-libs
- name: libv4l
  version: '>=0'
  category: media-libs
- name: libvpx
  version: '>=0'
  category: media-libs
- name: libwebp
  version: '>=0'
  category: media-libs
- name: openal
  version: '>=0'
  category: media-libs
- name: opencore-amr
  version: '>=0'
  category: media-libs
- name: openh264
  version: '>=0'
  category: media-libs
- name: openjpeg
  version: '>=0'
  category: media-libs-2
- name: opus
  version: '>=0'
  category: media-libs
- name: speex
  version: '>=0'
  category: media-libs
- name: vidstab
  version: '>=0'
  category: media-libs
- name: vo-amrwbenc
  version: '>=0'
  category: media-libs
- name: vulkan-loader
  version: '>=0'
  category: media-libs
- name: x264
  version: '>=0'
  category: media-libs
- name: x265
  version: '>=0'
  category: media-libs
- name: xvid
  version: '>=0'
  category: media-libs
- name: gsm
  version: '>=0'
  category: media-sound
- name: lame
  version: '>=0'
  category: media-sound
- name: twolame
  version: '>=0'
  category: media-sound
- name: rav1e
  version: '>=0'
  category: media-video
- name: srt
  version: '>=0'
  category: net-libs
- name: make
  version: '>=0'
  category: sys-devel
- name: linux-headers
  version: '>=0'
  category: sys-kernel
- name: libXv
  version: '>=0'
  category: x11-libs
- name: libva
  version: '>=0'
  category: x11-libs
- name: libvdpau
  version: '>=0'
  category: x11-libs
