steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: eselect-ruby
  version: '>=0'
  category: app-eselect
- name: tk
  version: '>=0'
  category: dev-lang
- name: jemalloc
  version: '>=0'
  category: dev-libs
- name: libffi
  version: '>=0'
  category: dev-libs
- name: libyaml
  version: '>=0'
  category: dev-libs
- name: systemtap
  version: '>=0'
  category: dev-util
- name: dante
  version: '>=0'
  category: net-proxy
- name: gcc
  version: '>=0'
  category: sys-devel-9.3.0
- name: db
  version: '>=0'
  category: sys-libs-5.3
- name: gdbm
  version: '>=0'
  category: sys-libs
