steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
package_dir: /{{ .Values.name }}
requires:
- name: eselect-ruby
  version: '>=0'
  category: app-eselect
- name: tk
  version: '>=0'
  category: dev-lang
- name: jemalloc
  version: '>=0'
  category: dev-libs
- name: libffi
  version: '>=0'
  category: dev-libs
- name: libyaml
  version: '>=0'
  category: dev-libs
- name: dante
  version: '>=0'
  category: net-proxy
- name: db
  version: '>=0'
  category: sys-libs-5.3
- name: gdbm
  version: '>=0'
  category: sys-libs
- name: zlib
  version: '>=0'
  category: sys-libs
