name: ansible
version: 2.10.0+4
category: app-admin
requires:
  - name: system-x
    version: '>=0'
    category: layers
  - name: paramiko
    version: '>=0'
    category: dev-python
  - name: pexpect
    version: '>=0'
    category: dev-python
  - name: netaddr
    version: '>=0'
    category: dev-python
  - name: sshpass
    version: '>=0'
    category: net-misc
  - name: pyyaml
    version: '>=0'
    category: dev-python
  - name: ansible-base
    version: '>=0'
    category: app-admin
  - name: httplib2
    version: '>=0'
    category: dev-python
labels:
  emerge.packages: app-admin/ansible
  original.package.name: app-admin/ansible
  original.package.version: 2.10.0-r2
