steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: wayland-protocols
  version: '>=0'
  category: dev-libs
- name: libepoxy
  version: '>=0'
  category: media-libs
- name: flex
  version: '>=0'
  category: sys-devel
- name: libunwind
  version: '>=0'
  category: sys-libs
- name: iceauth
  version: '>=0'
  category: x11-apps
- name: rgb
  version: '>=0'
  category: x11-apps
- name: xinit
  version: '>=0'
  category: x11-apps
- name: xkbcomp
  version: '>=0'
  category: x11-apps
- name: nvidia-drivers
  version: '>=0'
  category: x11-drivers
- name: libXaw
  version: '>=0'
  category: x11-libs
- name: libXfont2
  version: '>=0'
  category: x11-libs
- name: libXrender
  version: '>=0'
  category: x11-libs
- name: libXres
  version: '>=0'
  category: x11-libs
- name: libXtst
  version: '>=0'
  category: x11-libs
- name: libdmx
  version: '>=0'
  category: x11-libs
- name: libdrm
  version: '>=0'
  category: x11-libs
- name: libxshmfence
  version: '>=0'
  category: x11-libs
- name: pixman
  version: '>=0'
  category: x11-libs
- name: xcb-util-image
  version: '>=0'
  category: x11-libs
- name: xcb-util-keysyms
  version: '>=0'
  category: x11-libs
- name: xcb-util-renderutil
  version: '>=0'
  category: x11-libs
- name: xcb-util-wm
  version: '>=0'
  category: x11-libs
- name: xbitmaps
  version: '>=0'
  category: x11-misc
- name: xkeyboard-config
  version: '>=0'
  category: x11-misc
