steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: memcached
  version: '>=0'
  category: acct-user
- name: cyrus-sasl
  version: '>=0'
  category: dev-libs-2
- name: libevent
  version: '>=0'
  category: dev-libs
- name: selinux-memcached
  version: '>=0'
  category: sec-policy
- name: libseccomp
  version: '>=0'
  category: sys-libs
