steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: lua
  version: '>=0'
  category: dev-lang
- name: linguist-tools
  version: '>=0'
  category: dev-qt-5
- name: qtprintsupport
  version: '>=0'
  category: dev-qt-5
- name: qtsvg
  version: '>=0'
  category: dev-qt-5
- name: pgf
  version: '>=0'
  category: dev-tex
- name: texlive-latexrecommended
  version: '>=0'
  category: dev-texlive
- name: gd
  version: '>=0'
  category: media-libs-2
- name: libcaca
  version: '>=0'
  category: media-libs
- name: libggi
  version: '>=0'
  category: media-libs
- name: libcerf
  version: '>=0'
  category: sci-libs
- name: libXaw
  version: '>=0'
  category: x11-libs
- name: wxGTK
  version: '>=0'
  category: x11-libs-3.0-gtk3
