steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: messagebus
  version: '>=0'
  category: acct-user
- name: xmlto
  version: '>=0'
  category: app-text
- name: expat
  version: '>=0'
  category: dev-libs
- name: systemd
  version: '>=0'
  category: sys-apps
- name: elogind
  version: '>=0'
  category: sys-auth
- name: autoconf-archive
  version: '>=0'
  category: sys-devel
- name: libX11
  version: '>=0'
  category: x11-libs
- name: libXt
  version: '>=0'
  category: x11-libs
