steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: tbb
  version: '>=0'
  category: dev-cpp
- name: ois
  version: '>=0'
  category: dev-games
- name: boost
  version: '>=0'
  category: dev-libs
- name: poco
  version: '>=0'
  category: dev-libs
- name: tinyxml
  version: '>=0'
  category: dev-libs
- name: zziplib
  version: '>=0'
  category: dev-libs
- name: nvidia-cg-toolkit
  version: '>=0'
  category: media-gfx
- name: freeimage
  version: '>=0'
  category: media-libs
- name: freetype
  version: '>=0'
  category: media-libs-2
- name: mesa
  version: '>=0'
  category: media-libs
