steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: libvirt
  version: '>=0'
  category: acct-group
- name: qemu
  version: '>=0'
  category: acct-user
- name: xen
  version: '>=0'
  category: app-emulation
- name: scrub
  version: '>=0'
  category: app-misc
- name: xhtml1
  version: '>=0'
  category: app-text
- name: XML-XPath
  version: '>=0'
  category: dev-perl
- name: docutils
  version: '>=0'
  category: dev-python
- name: openbsd-netcat
  version: '>=0'
  category: net-analyzer
- name: wireshark
  version: '>=0'
  category: net-analyzer
- name: dnsmasq
  version: '>=0'
  category: net-dns
- name: firewalld
  version: '>=0'
  category: net-firewall
- name: nfs-utils
  version: '>=0'
  category: net-fs
- name: radvd
  version: '>=0'
  category: net-misc
- name: dmidecode
  version: '>=0'
  category: sys-apps
- name: iproute2
  version: '>=0'
  category: sys-apps
- name: polkit
  version: '>=0'
  category: sys-auth
- name: open-iscsi
  version: '>=0'
  category: sys-block
- name: parted
  version: '>=0'
  category: sys-block
- name: libapparmor
  version: '>=0'
  category: sys-libs
- name: audit
  version: '>=0'
  category: sys-process
- name: numad
  version: '>=0'
  category: sys-process
