steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: dvipng
  version: '>=0'
  category: app-text
- name: ghostscript-gpl
  version: '>=0'
  category: app-text
- name: poppler
  version: '>=0'
  category: app-text
- name: PyQt5
  version: '>=0'
  category: dev-python
- name: cairocffi
  version: '>=0'
  category: dev-python
- name: certifi
  version: '>=0'
  category: dev-python
- name: cycler
  version: '>=0'
  category: dev-python
- name: kiwisolver
  version: '>=0'
  category: dev-python
- name: numpy
  version: '>=0'
  category: dev-python
- name: pillow
  version: '>=0'
  category: dev-python
- name: pygobject
  version: '>=0'
  category: dev-python-3
- name: pyparsing
  version: '>=0'
  category: dev-python
- name: python-dateutil
  version: '>=0'
  category: dev-python
- name: pytz
  version: '>=0'
  category: dev-python
- name: versioneer
  version: '>=0'
  category: dev-python
- name: wxpython
  version: '>=0'
  category: dev-python-4.0
- name: xlwt
  version: '>=0'
  category: dev-python
- name: texlive-fontsrecommended
  version: '>=0'
  category: dev-texlive
- name: texlive-xetex
  version: '>=0'
  category: dev-texlive
- name: dejavu
  version: '>=0'
  category: media-fonts
- name: stix-fonts
  version: '>=0'
  category: media-fonts
- name: qhull
  version: '>=0'
  category: media-libs
- name: tornado
  version: '>=0'
  category: www-servers
