steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: libarchive
  version: '>=0'
  category: app-arch
- name: gnupg
  version: '>=0'
  category: app-crypt
- name: lua
  version: '>=0'
  category: dev-lang
- name: python
  version: '>=0'
  category: dev-lang-3.7
- name: python-exec
  version: '>=0'
  category: dev-lang-2
- name: elfutils
  version: '>=0'
  category: dev-libs
- name: nss
  version: '>=0'
  category: dev-libs
- name: popt
  version: '>=0'
  category: dev-libs
- name: dbus
  version: '>=0'
  category: sys-apps
- name: db
  version: '>=0'
  category: sys-libs-5.3
- name: libcap
  version: '>=0'
  category: sys-libs
