package_dir: /pkgdir/{{ .Values.name | replace "-portage" "" }}
includes:
- ^/var/db/pkg
- ^/var/db$
- ^/var$
requires:
- name: openpgp-keys-danielveillard
  version: "20210514"
  category: app-crypt
