image: scratch
env:
- LUET_YES=true
- LUET_NOLOCK=true
- HTTP_TIMEOUT=0
- JOBS=5
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
reuires:
  - category: seed
    name: mos-portage-stage
    version: ">=0"

prelude:
- >-
  eval 'mkdir -p /etc/portage/package.use/ || true' &&
  cp -rvf package.use/* /etc/portage/package.use/ &&
  emerge -t -j $JOBS {{ ( index .Values.labels "emerge.packages" ) }} &&
  rm -v /var/cache/distfiles/* /var/cache/binpkgs/* || true

