env:
- LUET_YES=true
- LUET_NOLOCK=true
- HTTP_TIMEOUT=0
- JOBS=5
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
requires:
  - category: seed
    name: mos-portage-base
    version: ">=0"

prelude:
# links is a buildtime req of xdg-utils not present on ebuild.
- >-
  eval 'mkdir -p /etc/portage/package.use/ || true' &&
  eval 'mkdir -p /etc/portage/package.license/ || true' &&
  cp -rvf package.use/* /etc/portage/package.use/ &&
  cp -rvf package.license/* /etc/portage/package.license/ &&
  USE="-cairo -harfbuzz" emerge -1 -j $JOBS media-libs/harfbuzz media-libs/freetype -t &&
  emerge -1 -j $JOBS dev-lang/rust-bin www-client/links -t &&
  sed -e 's|fontforge -script|#fontforge -script|g' -i
  /var/db/repos/gentoo/media-fonts/arphicfonts/arphicfonts-0.2.20080216.1-r2.ebuild &&
  USE="harfbuzz -zeroconf -vulkan" emerge fontforge -j $JOBS -t &&
  USE="-vaapi" emerge -1 -j $JOBS media-libs/mesa -t &&
  emerge -1 -j $JOBS dev-tex/bibtexu gst-plugins-base media-plugins/gst-plugins-pulse -t &&
  emerge -t -j $JOBS {{ ( index .Values.labels "emerge.packages" ) }} &&
  rm -v /var/cache/distfiles/* /var/cache/binpkgs/* || true

