steps:
- |
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- LUET_PORTAGE_PKGFILES=0
- LUET_PORTAGE_PKGMETA=1
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
package_dir: /{{ .Values.name }}
requires:
- name: autoconf-archive
  version: 2019.01.06
  category: sys-devel
