requires:
- category: "seed"
  name: "funtoo-base"
  version: "{{ .Values.version }}"
package_dir: /{{ .Values.name }}
steps:
- >-
  mkdir -p /{{ .Values.name }}/usr/share/mocaccino/layers/{{ .Values.name }}/entities/ &&
  entities dump -t /{{ .Values.name }}/usr/share/mocaccino/layers/{{ .Values.name }}/entities/ &&
  qlist -ICSv > /{{ .Values.name }}/usr/share/mocaccino/layers/{{ .Values.name }}/pkgslist

