steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: brotli
  version: '>=0'
  category: app-arch
- name: sqlite
  version: '>=0'
  category: dev-db-3
- name: vala
  version: '>=0'
  category: dev-lang-0.48
- name: gobject-introspection
  version: '>=0'
  category: dev-libs
- name: glib-utils
  version: '>=0'
  category: dev-util
- name: samba
  version: '>=0'
  category: net-fs
- name: libpsl
  version: '>=0'
  category: net-libs
