steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: dvipsk
  version: '>=0'
  category: app-text
- name: texlive-fontsrecommended
  version: '>=0'
  category: dev-texlive
- name: texlive-latexextra
  version: '>=0'
  category: dev-texlive
- name: texlive-plaingeneric
  version: '>=0'
  category: dev-texlive
