steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
package_dir: /{{ .Values.name }}
requires:
- name: libgphoto2
  version: '>=0'
  category: media-libs
- name: libv4l
  version: '>=0'
  category: media-libs
- name: tiff
  version: '>=0'
  category: media-libs
- name: net-snmp
  version: '>=0'
  category: net-analyzer
- name: avahi
  version: '>=0'
  category: net-dns
- name: curl
  version: '>=0'
  category: net-misc
- name: systemd
  version: '>=0'
  category: sys-apps
- name: xinetd
  version: '>=0'
  category: sys-apps
- name: autoconf-archive
  version: '>=0'
  category: sys-devel
- name: linux-headers
  version: '>=0'
  category: sys-kernel
- name: libieee1284
  version: '>=0'
  category: sys-libs
