steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: ghostscript-gpl
  version: '>=0'
  category: app-text
- name: poppler
  version: '>=0'
  category: app-text
- name: ruby
  version: '>=0'
  category: dev-lang-2.6
- name: swig
  version: '>=0'
  category: dev-lang
- name: qtprintsupport
  version: '>=0'
  category: dev-qt-5
- name: guile
  version: '>=0'
  category: dev-scheme-12
- name: librsvg
  version: '>=0'
  category: gnome-base-2
- name: devil
  version: '>=0'
  category: media-libs
- name: gd
  version: '>=0'
  category: media-libs-2
- name: lasi
  version: '>=0'
  category: media-libs
- name: gts
  version: '>=0'
  category: sci-libs
- name: flex
  version: '>=0'
  category: sys-devel
- name: libXaw
  version: '>=0'
  category: x11-libs
