steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: brotli
  version: '>=0'
  category: app-arch
- name: ca-certificates
  version: '>=0'
  category: app-misc
- name: nss
  version: '>=0'
  category: dev-libs
- name: libmetalink
  version: '>=0'
  category: media-libs
- name: rtmpdump
  version: '>=0'
  category: media-video
- name: libidn2
  version: '>=0'
  category: net-dns
- name: libssh2
  version: '>=0'
  category: net-libs
- name: nghttp2
  version: '>=0'
  category: net-libs
- name: openldap
  version: '>=0'
  category: net-nds
