steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: libsecret
  version: '>=0'
  category: app-crypt
- name: eselect-pinentry
  version: '>=0'
  category: app-eselect
- name: libassuan
  version: '>=0'
  category: dev-libs
- name: qtwidgets
  version: '>=0'
  category: dev-qt-5
- name: libcap
  version: '>=0'
  category: sys-libs
- name: ncurses
  version: '>=0'
  category: sys-libs
- name: fltk
  version: '>=0'
  category: x11-libs-1
