steps:
- |
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- LUET_PORTAGE_PKGFILES=0
- LUET_PORTAGE_PKGMETA=1
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
package_dir: /{{ .Values.name }}
requires:
- name: eselect-ruby
  version: "20190121"
  category: app-eselect
