steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: djvu
  version: '>=0'
  category: app-text
- name: corefonts
  version: '>=0'
  category: media-fonts
- name: graphicsmagick
  version: '>=0'
  category: media-gfx
- name: graphviz
  version: '>=0'
  category: media-gfx
- name: potrace
  version: '>=0'
  category: media-gfx
- name: libheif
  version: '>=0'
  category: media-libs
- name: liblqr
  version: '>=0'
  category: media-libs
- name: libraw
  version: '>=0'
  category: media-libs
- name: openexr
  version: '>=0'
  category: media-libs
- name: fftw
  version: '>=0'
  category: sci-libs-3.0
