steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: doxygen
  version: '>=0'
  category: app-doc
- name: pathlib2
  version: '>=0'
  category: dev-python
- name: six
  version: '>=0'
  category: dev-python
- name: wxGTK
  version: '>=0'
  category: x11-libs-3.0
