steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: python-exec
  version: '>=0'
  category: dev-lang-2
- name: libltdl
  version: '>=0'
  category: dev-libs
- name: freetype
  version: '>=0'
  category: media-libs-2
- name: giflib
  version: '>=0'
  category: media-libs
- name: libpng
  version: '>=0'
  category: media-libs
- name: libuninameslist
  version: '>=0'
  category: media-libs
- name: tiff
  version: '>=0'
  category: media-libs
- name: woff2
  version: '>=0'
  category: media-libs
- name: cairo
  version: '>=0'
  category: x11-libs
- name: gtk+
  version: '>=0'
  category: x11-libs-3
- name: libX11
  version: '>=0'
  category: x11-libs
- name: libXi
  version: '>=0'
  category: x11-libs
- name: pango
  version: '>=0'
  category: x11-libs
