steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: dnspython
  version: '>=0'
  category: dev-python
- name: greenlet
  version: '>=0'
  category: dev-python
- name: monotonic
  version: '>=0'
  category: dev-python
- name: nose
  version: '>=0'
  category: dev-python
- name: pyopenssl
  version: '>=0'
  category: dev-python
- name: python-docs
  version: '>=0'
  category: dev-python-3.8
