steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: bzip2
  version: '>=0'
  category: app-arch
- name: xz-utils
  version: '>=0'
  category: app-arch
- name: sqlite
  version: '>=0'
  category: dev-db-3
- name: expat
  version: '>=0'
  category: dev-libs
- name: libffi
  version: '>=0'
  category: dev-libs
- name: blt
  version: '>=0'
  category: dev-tcltk
- name: tix
  version: '>=0'
  category: dev-tcltk
- name: bluez
  version: '>=0'
  category: net-wireless
- name: util-linux
  version: '>=0'
  category: sys-apps
- name: gcc
  version: '>=0'
  category: sys-devel-9.3.0
- name: gdbm
  version: '>=0'
  category: sys-libs
