steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  eval 'rm -rf /{{ .Values.name }} || true' && mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
requires:
- name: bzip2
  version: '>=0'
  category: app-arch
- name: xz-utils
  version: '>=0'
  category: app-arch
- name: sqlite
  version: '>=0'
  category: dev-db-3
- name: expat
  version: '>=0'
  category: dev-libs
- name: libffi
  version: '>=0'
  category: dev-libs
- name: bluez
  version: '>=0'
  category: net-wireless
- name: util-linux
  version: '>=0'
  category: sys-apps
- name: gdbm
  version: '>=0'
  category: sys-libs
- name: zlib
  version: '>=0'
  category: sys-libs
- name: libcrypt
  version: '>=0'
  category: virtual
- name: libintl
  version: '>=0'
  category: virtual
