package_dir: /pkgdir/{{ .Values.name }}
prelude:
- >-
  mkdir -p
  /pkgdir/{{ .Values.name }}/var/db/repos
  /pkgdir/{{ .Values.name }}/var/cache/binpkgs
  /pkgdir/{{ .Values.name }}/var/cache/distfiles
- >-
  cp -rf /usr/portage /pkgdir/{{ .Values.name }} &&
  cp -rf /var/db/repos/gentoo /pkgdir/var/db/repos/
requires:
- category: "seed"
  version:  ">=0"
  name:     "gentoo-portage"
