steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: video
  version: '>=0'
  category: acct-group
- name: atk
  version: '>=0'
  category: dev-libs
- name: glib
  version: '>=0'
  category: dev-libs-2
- name: jansson
  version: '>=0'
  category: dev-libs
- name: dbus
  version: '>=0'
  category: sys-apps
- name: pciutils
  version: '>=0'
  category: sys-apps
- name: sed
  version: '>=0'
  category: sys-apps
- name: glibc
  version: '>=0'
  category: sys-libs-2.2
- name: cairo
  version: '>=0'
  category: x11-libs
- name: gdk-pixbuf
  version: '>=0'
  category: x11-libs-2
- name: gtk+
  version: '>=0'
  category: x11-libs-3
- name: libXext
  version: '>=0'
  category: x11-libs
- name: libXrandr
  version: '>=0'
  category: x11-libs
- name: libXv
  version: '>=0'
  category: x11-libs
- name: libXxf86vm
  version: '>=0'
  category: x11-libs
- name: pango
  version: '>=0'
  category: x11-libs
