steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: sqlite
  version: '>=0'
  category: dev-db-3
- name: libressl
  version: '>=0'
  category: dev-libs
- name: pypy-exe-bin
  version: '>=0'
  category: dev-python-7.3.1
- name: tix
  version: '>=0'
  category: dev-tcltk
- name: gdbm
  version: '>=0'
  category: sys-libs
