steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: zstd
  version: '>=0'
  category: app-arch
- name: poppler
  version: '>=0'
  category: app-text
- name: oracle-instantclient
  version: '>=0'
  category: dev-db
- name: postgresql
  version: '>=0'
  category: dev-db-12
- name: spatialite
  version: '>=0'
  category: dev-db
- name: unixODBC
  version: '>=0'
  category: dev-db
- name: ant-core
  version: '>=0'
  category: dev-java
- name: jackcess
  version: '>=0'
  category: dev-java-1
- name: json-c
  version: '>=0'
  category: dev-libs
- name: xerces-c
  version: '>=0'
  category: dev-libs
- name: numpy
  version: '>=0'
  category: dev-python
- name: libwebp
  version: '>=0'
  category: media-libs
- name: armadillo
  version: '>=0'
  category: sci-libs
- name: cfitsio
  version: '>=0'
  category: sci-libs
- name: libgeotiff
  version: '>=0'
  category: sci-libs
- name: netcdf
  version: '>=0'
  category: sci-libs
- name: ogdi
  version: '>=0'
  category: sci-libs
