package_dir: /pkgdir/{{ .Values.name | replace "-portage" "" }}
includes:
- ^/var/db/pkg
- ^/var/db$
- ^/var$
requires:
- name: font-bh-lucidatypewriter-100dpi
  version: 1.0.3
  category: media-fonts
