steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: gdbus-codegen
  version: '>=0'
  category: dev-util
- name: gtk-doc
  version: '>=0'
  category: dev-util
- name: meson
  version: '>=0'
  category: dev-util
- name: ninja
  version: '>=0'
  category: dev-util
- name: systemtap
  version: '>=0'
  category: dev-util
