steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: newt
  version: '>=0'
  category: dev-libs
- name: dnsmasq
  version: '>=0'
  category: net-dns
- name: openresolv
  version: '>=0'
  category: net-dns
- name: libndp
  version: '>=0'
  category: net-libs
- name: dhcp
  version: '>=0'
  category: net-misc
- name: dhcpcd
  version: '>=0'
  category: net-misc
- name: iputils
  version: '>=0'
  category: net-misc
- name: libteam
  version: '>=0'
  category: net-misc
- name: modemmanager
  version: '>=0'
  category: net-misc
- name: ofono
  version: '>=0'
  category: net-misc
- name: elogind
  version: '>=0'
  category: sys-auth
- name: xhost
  version: '>=0'
  category: x11-apps
- name: xorg-server
  version: '>=0'
  category: x11-base
