steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: nofiles
  version: '>=0'
  category: acct-group
- name: qmail
  version: '>=0'
  category: acct-group
- name: alias
  version: '>=0'
  category: acct-user
- name: qmaild
  version: '>=0'
  category: acct-user
- name: qmaill
  version: '>=0'
  category: acct-user
- name: qmailp
  version: '>=0'
  category: acct-user
- name: qmailq
  version: '>=0'
  category: acct-user
- name: qmailr
  version: '>=0'
  category: acct-user
- name: qmails
  version: '>=0'
  category: acct-user
- name: libidn2
  version: '>=0'
  category: net-dns
- name: queue-repair
  version: '>=0'
  category: net-mail
- name: gentoo-functions
  version: '>=0'
  category: sys-apps
- name: groff
  version: '>=0'
  category: sys-apps
