image: scratch
env:
- LUET_YES=true
- LUET_NOLOCK=true
copy:
  - package:
      category: seed
      name: mos-portage-stage
      version: ">=0"
    source: "/mos-portage"
    destination: "/"
prelude:
- >-
  touch /etc/shadow &&
  touch /etc/group &&
  touch /etc/gshadow &&
  touch /etc/passwd &&
  entities merge -s /usr/share/mocaccino/entities/acct-core/ -a &&
  yq w /etc/luet/luet.yaml 'system.rootfs' '/' -i &&
  luet install
  system/luet-extensions-live
  system/luet-devkit
  dev-util/pkgs-checker-minimal &&
  luet cleanup

# Using steps to trace what files are generated
# by gcc-config/binutils-config.
steps:
# sed -e 's|\[\[ \! -w ${EROOT}.*|# Check dropped for error with docker|g' -i /usr/bin/gcc-config &&
- >-
  cp make.conf /etc/portage/ &&
  cd /usr/bin &&
  ln -s gawk awk &&
  rm -rf /luetbuild &&
  /usr/bin/gcc-config 1 &&
  source /etc/profile &&
  eselect gcc set 1 &&
  eselect binutils set 1 &&
  eselect profile set default/linux/amd64/17.1/desktop/systemd &&
  mkdir -p /var/lib/portage &&
  echo "Europe/Rome" > /etc/localtime &&
  env-update &&
  ldconfig &&
  eval 'locale-gen || true' &&

excludes:
- ^/etc/gshadow
- ^/etc/group
- ^/etc/passwd
- ^/etc/shadow
- ^/etc/ld.so.cache
- ^/etc/ld.so.conf
- ^/etc/locatime
- ^/var/cache/ldconfig/aux-cache

