steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: cloudpickle
  version: '>=0'
  category: dev-python
- name: loky
  version: '>=0'
  category: dev-python
- name: lz4
  version: '>=0'
  category: dev-python
- name: matplotlib
  version: '>=0'
  category: dev-python
- name: numpydoc
  version: '>=0'
  category: dev-python
- name: pandas
  version: '>=0'
  category: dev-python
- name: sphinx-gallery
  version: '>=0'
  category: dev-python
- name: threadpoolctl
  version: '>=0'
  category: dev-python
