steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: yudit
  version: '>=0'
  category: app-editors
- name: tracker
  version: '>=0'
  category: app-misc
- name: dbus-glib
  version: '>=0'
  category: dev-libs
- name: avahi
  version: '>=0'
  category: net-dns
- name: openldap
  version: '>=0'
  category: net-nds
- name: coreutils
  version: '>=0'
  category: sys-apps
- name: cracklib
  version: '>=0'
  category: sys-libs
- name: pam
  version: '>=0'
  category: sys-libs
- name: tdb
  version: '>=0'
  category: sys-libs
