steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: DBD-Pg
  version: '>=0'
  category: dev-perl
- name: DBD-SQLite
  version: '>=0'
  category: dev-perl
- name: DBD-mysql
  version: '>=0'
  category: dev-perl
- name: HTML-Parser
  version: '>=0'
  category: dev-perl
- name: IO-Socket-INET6
  version: '>=0'
  category: dev-perl
- name: Net-DNS
  version: '>=0'
  category: dev-perl
- name: NetAddr-IP
  version: '>=0'
  category: dev-perl
- name: perl-ldap
  version: '>=0'
  category: dev-perl
