steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: brotli
  version: '>=0'
  category: app-arch
- name: bzip2
  version: '>=0'
  category: app-arch
- name: harfbuzz
  version: '>=0'
  category: media-libs
- name: libpng
  version: '>=0'
  category: media-libs
- name: zlib
  version: '>=0'
  category: sys-libs
- name: libX11
  version: '>=0'
  category: x11-libs
- name: libXau
  version: '>=0'
  category: x11-libs
- name: libXdmcp
  version: '>=0'
  category: x11-libs
