steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: gzip
  version: '>=0'
  category: app-arch
- name: emacs-common-gentoo
  version: '>=0'
  category: app-emacs
- name: eselect-emacs
  version: '>=0'
  category: app-eselect
- name: jansson
  version: '>=0'
  category: dev-libs
- name: m17n-lib
  version: '>=0'
  category: dev-libs
- name: gconf
  version: '>=0'
  category: gnome-base-2
- name: imagemagick
  version: '>=0'
  category: media-gfx
- name: alsa-lib
  version: '>=0'
  category: media-libs
- name: giflib
  version: '>=0'
  category: media-libs
- name: liblockfile
  version: '>=0'
  category: net-libs
- name: webkit-gtk
  version: '>=0'
  category: net-libs-4
- name: mailutils
  version: '>=0'
  category: net-mail
- name: libXaw3d
  version: '>=0'
  category: x11-libs
- name: motif
  version: '>=0'
  category: x11-libs
