steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: brotli
  version: '>=0'
  category: app-arch
- name: mime-types
  version: '>=0'
  category: app-misc
- name: apr
  version: '>=0'
  category: dev-libs-1
- name: libpcre
  version: '>=0'
  category: dev-libs-3
- name: nghttp2
  version: '>=0'
  category: net-libs
- name: openldap
  version: '>=0'
  category: net-nds
- name: gdbm
  version: '>=0'
  category: sys-libs
- name: libcap
  version: '>=0'
  category: sys-libs
