steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: brltty
  version: '>=0'
  category: app-accessibility
- name: spice
  version: '>=0'
  category: app-emulation
- name: xen-tools
  version: '>=0'
  category: app-emulation
- name: capstone
  version: '>=0'
  category: dev-libs
- name: nettle
  version: '>=0'
  category: dev-libs
- name: libpng
  version: '>=0'
  category: media-libs
- name: mesa
  version: '>=0'
  category: media-libs
- name: sdl2-image
  version: '>=0'
  category: media-libs
- name: virglrenderer
  version: '>=0'
  category: media-libs
- name: pulseaudio
  version: '>=0'
  category: media-sound
- name: libnfs
  version: '>=0'
  category: net-fs
- name: libiscsi
  version: '>=0'
  category: net-libs
- name: libslirp
  version: '>=0'
  category: net-libs
- name: libssh
  version: '>=0'
  category: net-libs
- name: vde
  version: '>=0'
  category: net-misc
- name: attr
  version: '>=0'
  category: sys-apps
- name: texinfo
  version: '>=0'
  category: sys-apps
- name: usbredir
  version: '>=0'
  category: sys-apps
- name: glusterfs
  version: '>=0'
  category: sys-cluster
- name: libibumad
  version: '>=0'
  category: sys-fabric-3.12
- name: edk2-ovmf
  version: '>=0'
  category: sys-firmware
- name: sgabios
  version: '>=0'
  category: sys-firmware
- name: multipath-tools
  version: '>=0'
  category: sys-fs
- name: libcap
  version: '>=0'
  category: sys-libs
- name: liburing
  version: '>=0'
  category: sys-libs
- name: libxkbcommon
  version: '>=0'
  category: x11-libs
- name: vte
  version: '>=0'
  category: x11-libs-2.91
