steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: vpopmail
  version: '>=0'
  category: acct-group
- name: vpopmail
  version: '>=0'
  category: acct-user
- name: mysql-connector-c
  version: '>=0'
  category: dev-db
- name: postgresql
  version: '>=0'
  category: dev-db-12
- name: maildrop
  version: '>=0'
  category: mail-filter
- name: spamassassin
  version: '>=0'
  category: mail-filter
