steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: libgcrypt
  version: '>=0'
  category: dev-libs
- name: skey
  version: '>=0'
  category: sys-auth
- name: sssd
  version: '>=0'
  category: sys-auth
- name: bison
  version: '>=0'
  category: sys-devel
- name: pam
  version: '>=0'
  category: sys-libs
- name: zlib
  version: '>=0'
  category: sys-libs
