steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: baselayout
  version: '>=0'
  category: sys-apps
- name: policycoreutils
  version: '>=0'
  category: sys-apps
- name: pambase
  version: '>=0'
  category: sys-auth
- name: udev-init-scripts
  version: '>=0'
  category: sys-fs
- name: audit
  version: '>=0'
  category: sys-process
- name: procps
  version: '>=0'
  category: sys-process
- name: psmisc
  version: '>=0'
  category: sys-process
