steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: gzip
  version: '>=0'
  category: app-arch
- name: expat
  version: '>=0'
  category: dev-libs
- name: libevent
  version: '>=0'
  category: dev-libs
- name: libxslt
  version: '>=0'
  category: dev-libs
- name: nss
  version: '>=0'
  category: dev-libs
- name: re2
  version: '>=0'
  category: dev-libs
- name: designer
  version: '>=0'
  category: dev-qt-5
- name: qtcore
  version: '>=0'
  category: dev-qt-5
- name: qtpositioning
  version: '>=0'
  category: dev-qt-5
- name: qtprintsupport
  version: '>=0'
  category: dev-qt-5
- name: qtwebchannel
  version: '>=0'
  category: dev-qt-5
- name: gperf
  version: '>=0'
  category: dev-util
- name: lcms
  version: '>=0'
  category: media-libs-2
- name: libjpeg-turbo
  version: '>=0'
  category: media-libs
- name: ffmpeg
  version: '>=0'
  category: media-video
- name: dbus
  version: '>=0'
  category: sys-apps
- name: pciutils
  version: '>=0'
  category: sys-apps
- name: bison
  version: '>=0'
  category: sys-devel
- name: libXScrnSaver
  version: '>=0'
  category: x11-libs
- name: libXcomposite
  version: '>=0'
  category: x11-libs
- name: libXcursor
  version: '>=0'
  category: x11-libs
