steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: unzip
  version: '>=0'
  category: app-arch
- name: xz-utils
  version: '>=0'
  category: app-arch
- name: pax-utils
  version: '>=0'
  category: app-misc
- name: freetype
  version: '>=0'
  category: media-libs-2
- name: libsdl
  version: '>=0'
  category: media-libs
- name: help2man
  version: '>=0'
  category: sys-apps
- name: ibm-powerpc-utils
  version: '>=0'
  category: sys-apps
- name: texinfo
  version: '>=0'
  category: sys-apps
- name: bison
  version: '>=0'
  category: sys-devel
- name: fuse
  version: '>=0'
  category: sys-fs-3
- name: lvm2
  version: '>=0'
  category: sys-fs
- name: zfs
  version: '>=0'
  category: sys-fs
