steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: physfs
  version: '>=0'
  category: dev-games
- name: dumb
  version: '>=0'
  category: media-libs
- name: flac
  version: '>=0'
  category: media-libs
- name: freetype
  version: '>=0'
  category: media-libs-2
- name: libvorbis
  version: '>=0'
  category: media-libs
- name: libwebp
  version: '>=0'
  category: media-libs
- name: openal
  version: '>=0'
  category: media-libs
- name: opus
  version: '>=0'
  category: media-libs
- name: libXxf86vm
  version: '>=0'
  category: x11-libs
