steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: designer
  version: '>=0'
  category: dev-qt-5
- name: qtsvg
  version: '>=0'
  category: dev-qt-5
- name: qttest
  version: '>=0'
  category: dev-qt-5
- name: qtx11extras
  version: '>=0'
  category: dev-qt-5
- name: kded
  version: '>=0'
  category: kde-frameworks-5
- name: kdoctools
  version: '>=0'
  category: kde-frameworks-5
