requires:
- category: "seed"
  name: "base"
  version: ">=0"
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- LUET_NOLOCK="true"
- LUET_YES="true"
prelude:
- >-
  source /etc/profile &&
  curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- >-
  luet install
  repository/mocaccino-extra-stable
  system/luet-extensions-live
  system/luet-devkit
  &&
  luet install dev-util/pkgs-checker-minimal utils/jq &&
  luet cleanup
