steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: ceph
  version: '>=0'
  category: acct-group
- name: ceph
  version: '>=0'
  category: acct-user
- name: cpio
  version: '>=0'
  category: app-arch
- name: jq
  version: '>=0'
  category: app-misc
- name: bash
  version: '>=0'
  category: app-shells
- name: yaml-cpp
  version: '>=0'
  category: dev-cpp
- name: yasm
  version: '>=0'
  category: dev-lang
- name: boost
  version: '>=0'
  category: dev-libs
- name: crypto++
  version: '>=0'
  category: dev-libs
- name: expat
  version: '>=0'
  category: dev-libs
- name: jemalloc
  version: '>=0'
  category: dev-libs
- name: leveldb
  version: '>=0'
  category: dev-libs
- name: libaio
  version: '>=0'
  category: dev-libs
- name: libnl
  version: '>=0'
  category: dev-libs-3
- name: librdkafka
  version: '>=0'
  category: dev-libs
- name: protobuf
  version: '>=0'
  category: dev-libs
- name: cython
  version: '>=0'
  category: dev-python
- name: sphinx
  version: '>=0'
  category: dev-python
- name: babeltrace
  version: '>=0'
  category: dev-util
- name: cunit
  version: '>=0'
  category: dev-util
- name: gperf
  version: '>=0'
  category: dev-util
- name: lttng-ust
  version: '>=0'
  category: dev-util
- name: ragel
  version: '>=0'
  category: dev-util
- name: gnutls
  version: '>=0'
  category: net-libs
- name: rabbitmq-c
  version: '>=0'
  category: net-libs
- name: curl
  version: '>=0'
  category: net-misc
- name: coreutils
  version: '>=0'
  category: sys-apps
- name: findutils
  version: '>=0'
  category: sys-apps
- name: grep
  version: '>=0'
  category: sys-apps
- name: hwloc
  version: '>=0'
  category: sys-apps
- name: keyutils
  version: '>=0'
  category: sys-apps
- name: sed
  version: '>=0'
  category: sys-apps
- name: which
  version: '>=0'
  category: sys-apps
- name: oath-toolkit
  version: '>=0'
  category: sys-auth
- name: bc
  version: '>=0'
  category: sys-devel
- name: make
  version: '>=0'
  category: sys-devel
- name: patch
  version: '>=0'
  category: sys-devel
- name: fuse
  version: '>=0'
  category: sys-fs-3
- name: xfsprogs
  version: '>=0'
  category: sys-fs
- name: zfs
  version: '>=0'
  category: sys-fs
- name: libcap-ng
  version: '>=0'
  category: sys-libs
