steps:
- |
  eval 'rm -rf /pkgdir/ || true' && mkdir /pkgdir/{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- LUET_PORTAGE_PKGFILES=0
- LUET_PORTAGE_PKGMETA=1
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
package_dir: /pkgdir/{{ .Values.name }}
requires:
- name: openpgp-keys-python
  version: "20210121"
  category: app-crypt
