steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: docbook-xml-dtd
  version: '>=0'
  category: app-text-4.5
- name: docbook-xsl-stylesheets
  version: '>=0'
  category: app-text
- name: sgml-common
  version: '>=0'
  category: app-text
- name: libxml2
  version: '>=0'
  category: dev-libs-2
- name: libxslt
  version: '>=0'
  category: dev-libs
- name: URI
  version: '>=0'
  category: dev-perl
- name: ki18n
  version: '>=0'
  category: kde-frameworks-5
