steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: opencc
  version: '>=0'
  category: app-i18n
- name: enchant
  version: '>=0'
  category: app-text-2
- name: iso-codes
  version: '>=0'
  category: app-text
- name: lua
  version: '>=0'
  category: dev-lang
- name: extra-cmake-modules
  version: '>=0'
  category: kde-frameworks-5
- name: dbus
  version: '>=0'
  category: sys-apps
- name: gtk+
  version: '>=0'
  category: x11-libs-3
- name: libxkbfile
  version: '>=0'
  category: x11-libs
- name: xkeyboard-config
  version: '>=0'
  category: x11-misc
