steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: gzip
  version: '>=0'
  category: app-arch
- name: pax-utils
  version: '>=0'
  category: app-misc
- name: gd
  version: '>=0'
  category: media-libs-2
- name: openssh
  version: '>=0'
  category: net-misc
- name: grep
  version: '>=0'
  category: sys-apps
- name: gcc
  version: '>=0'
  category: sys-devel-9.3.0
