steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  eval 'rm -rf /{{ .Values.name }} || true' && mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
requires:
- name: fcitx
  version: '>=0'
  category: app-i18n-4
- name: ibus
  version: '>=0'
  category: app-i18n
- name: vulkan-headers
  version: '>=0'
  category: dev-util
- name: libsamplerate
  version: '>=0'
  category: media-libs
- name: nas
  version: '>=0'
  category: media-libs
- name: pulseaudio
  version: '>=0'
  category: media-sound
- name: glu
  version: '>=0'
  category: virtual
- name: libudev
  version: '>=0'
  category: virtual
- name: opengl
  version: '>=0'
  category: virtual
- name: libXScrnSaver
  version: '>=0'
  category: x11-libs
- name: libXcursor
  version: '>=0'
  category: x11-libs
- name: libXinerama
  version: '>=0'
  category: x11-libs
- name: tslib
  version: '>=0'
  category: x11-libs
