steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: mariadb-connector-c
  version: '>=0'
  category: dev-db
- name: postgresql
  version: '>=0'
  category: dev-db-12
- name: apr
  version: '>=0'
  category: dev-libs-1
- name: expat
  version: '>=0'
  category: dev-libs
- name: nss
  version: '>=0'
  category: dev-libs
- name: gdbm
  version: '>=0'
  category: sys-libs
