steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
package_dir: /{{ .Values.name }}
requires:
- name: libxdg-basedir
  version: '>=0'
  category: dev-libs
- name: a52dec
  version: '>=0'
  category: media-libs
- name: faad2
  version: '>=0'
  category: media-libs
- name: flac
  version: '>=0'
  category: media-libs
- name: libdca
  version: '>=0'
  category: media-libs
- name: libdvdcss
  version: '>=0'
  category: media-libs-1.2
- name: libdvdnav
  version: '>=0'
  category: media-libs
- name: libfame
  version: '>=0'
  category: media-libs
- name: libmad
  version: '>=0'
  category: media-libs
- name: libmng
  version: '>=0'
  category: media-libs
- name: musepack-tools
  version: '>=0'
  category: media-sound
- name: ffmpeg
  version: '>=0'
  category: media-video
- name: vcdimager
  version: '>=0'
  category: media-video
- name: gdk-pixbuf
  version: '>=0'
  category: x11-libs-2
- name: libXinerama
  version: '>=0'
  category: x11-libs
- name: libXvMC
  version: '>=0'
  category: x11-libs
