steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: scim
  version: '>=0'
  category: app-i18n
- name: libspectre
  version: '>=0'
  category: app-text
- name: poppler
  version: '>=0'
  category: app-text
- name: lua
  version: '>=0'
  category: dev-lang
- name: luajit
  version: '>=0'
  category: dev-lang-2
- name: fribidi
  version: '>=0'
  category: dev-libs
- name: hyphen
  version: '>=0'
  category: dev-libs
- name: libinput
  version: '>=0'
  category: dev-libs
- name: gst-plugins-base
  version: '>=0'
  category: media-libs-1.0
- name: libraw
  version: '>=0'
  category: media-libs
- name: libv4l
  version: '>=0'
  category: media-libs
- name: rlottie
  version: '>=0'
  category: media-libs
- name: libvncserver
  version: '>=0'
  category: net-libs
- name: connman
  version: '>=0'
  category: net-misc
- name: bullet
  version: '>=0'
  category: sci-physics
- name: libXcomposite
  version: '>=0'
  category: x11-libs
- name: libXpm
  version: '>=0'
  category: x11-libs
- name: libXpresent
  version: '>=0'
  category: x11-libs
