steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: glog
  version: '>=0'
  category: dev-cpp
- name: ogre
  version: '>=0'
  category: dev-games
- name: protobuf
  version: '>=0'
  category: dev-libs
- name: qtconcurrent
  version: '>=0'
  category: dev-qt-5
- name: qttest
  version: '>=0'
  category: dev-qt-5
- name: gst-plugins-base
  version: '>=0'
  category: media-libs-1.0
- name: libgphoto2
  version: '>=0'
  category: media-libs
- name: openexr
  version: '>=0'
  category: media-libs
- name: xine-lib
  version: '>=0'
  category: media-libs-1
- name: vtk
  version: '>=0'
  category: sci-libs
