requires:
- category: "seed"
  name: "gentoo-portage"
  version: ">=0"
unpack: true
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS=5

prelude:
- >-
  source /etc/profile &&
  cp -rvf package.use /etc/portage/ &&
  cp -rvf profile /etc/portage/ &&
  cp -rvf make.conf /etc/portage/ &&
  cp -rvf package.accept_keywords /etc/portage/ &&
  cp -rvf package.license /etc/portage/ &&
  cp -rvf package.mask /etc/portage/ &&
  cp -rvf env /etc/portage/ &&
  cp -rvf package.env /etc/portage/
- >-
  source /etc/profile &&
  emerge -1 dev-libs/libgcrypt:0 -j $JOBS -t &&
  emerge -1 dev-libs/openssl net-misc/openssh -j $JOBS -t &&
  emerge -1 dev-lang/rust-bin -j $JOBS -t &&
  emerge -1
  app-arch/libarchive
  app-arch/xz-utils
  dev-python/setuptools:0
  dev-python/setuptools_scm:0
  dev-python/certifi:0
  dev-python/jinja
  dev-util/meson
  dev-python/cffi
  dev-python/toml
  dev-python/urllib3
  dev-python/requests
  --backtrack=100 -j $JOBS -t &&
  emerge -1 sys-apps/portage -j $JOBS -t

- >-
  source /etc/profile &&
  emerge -1 sys-apps/systemd -j $JOBS -t &&
  emerge -1uDN @system -t -j $JOBS &&
  emerge -uDN -t --with-bdeps=y --backtrack=100 --autounmask-keep-masks=y @world -j $JOBS -t &&
  etc-update -q --automode -5 &&
  chmod -R 0700 /{etc,usr/share}/polkit-1/rules.d &&
  chown -R 102:0 /{etc,usr/share}/polkit-1/rules.d &&
  rm -v /var/cache/distfiles/*
