steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: at-spi2-core
  version: '>=0'
  category: app-accessibility-2
- name: libsecret
  version: '>=0'
  category: app-crypt
- name: enchant
  version: '>=0'
  category: app-text-2
- name: hyphen
  version: '>=0'
  category: dev-libs
- name: libtasn1
  version: '>=0'
  category: dev-libs
- name: wpebackend-fdo
  version: '>=0'
  category: gui-libs-1.0
- name: libwebp
  version: '>=0'
  category: media-libs
- name: openjpeg
  version: '>=0'
  category: media-libs-2
- name: woff2
  version: '>=0'
  category: media-libs
- name: gst-plugins-opus
  version: '>=0'
  category: media-plugins-1.0
- name: libsoup
  version: '>=0'
  category: net-libs-2.4
- name: bubblewrap
  version: '>=0'
  category: sys-apps
- name: xdg-dbus-proxy
  version: '>=0'
  category: sys-apps
- name: gtk+
  version: '>=0'
  category: x11-libs-3
- name: libXt
  version: '>=0'
  category: x11-libs
- name: libnotify
  version: '>=0'
  category: x11-libs
