steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
package_dir: /{{ .Values.name }}
requires:
- name: at-spi2-core
  version: '>=0'
  category: app-accessibility-2
- name: speech-dispatcher
  version: '>=0'
  category: app-accessibility
- name: java-config
  version: '>=0'
  category: dev-java-2
- name: icu
  version: '>=0'
  category: dev-libs
- name: liblouis
  version: '>=0'
  category: dev-libs
- name: findlib
  version: '>=0'
  category: dev-ml
- name: cython
  version: '>=0'
  category: dev-python
- name: polkit
  version: '>=0'
  category: sys-auth
- name: libXaw
  version: '>=0'
  category: x11-libs
- name: libXfixes
  version: '>=0'
  category: x11-libs
