steps:
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  mkdir /{{ .Values.name }} && \
  luet portage -- --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES=/var/cache/binpkgs
package_dir: /{{ .Values.name }}
requires:
- name: dieharder
  version: '>=0'
  category: app-crypt
- name: p11-kit
  version: '>=0'
  category: app-crypt
- name: datefudge
  version: '>=0'
  category: app-misc
- name: nettle
  version: '>=0'
  category: dev-libs
- name: softhsm
  version: '>=0'
  category: dev-libs-2
- name: guile
  version: '>=0'
  category: dev-scheme-12
- name: ppp
  version: '>=0'
  category: net-dialup
- name: libidn2
  version: '>=0'
  category: net-dns
- name: unbound
  version: '>=0'
  category: net-dns
- name: socat
  version: '>=0'
  category: net-misc
- name: autogen
  version: '>=0'
  category: sys-devel
- name: libseccomp
  version: '>=0'
  category: sys-libs
